### PR TITLE
Proposal: nested functions/closures. (and a Treesort program)

### PR DESCRIPTION
**Pull request by zhuowei**
## Background
[wolfgang42's Rockstar-JavaScript transpiler](https://github.com/wolfgang42/rockstar-js/tree/25a83efaa551681d7d939723267d80257139c8ca) doesn't support objects, but, since it compiles to JavaScript, I found that it does support nested functions, and thus closures.

[Aphyr](https://aphyr.com/posts/340-reversing-the-technical-interview) demonstrated that closures can be used to implement data structures.

## Experiment

To demonstrate the usefulness of closures, I implemented Treesort in Rockstar as implemented by wolfgang42's transpiler.

I first [wrote this in Python 3](https://gist.github.com/zhuowei/6eddebc142cdeb74289bdcd9dab88269
) from [Wikipedia's example on treesort](https://en.wikipedia.org/wiki/Tree_sort#Example), then ported it line by line to Rockstar.

When run with wolfgang42's transpiler , the program prints

```
$ yarn run transpile examples/treesort.rock 
yarn run v1.6.0
$ node ./src/rockstar.js examples/treesort.rock
✨  Done in 0.28s.        
$ node examples/treesort.js 
822
4805
9117
10097
10402
13586
20636
24037
24805
32533
34673
37542
39292
54876
64894
74296
74945
76520
80959
91665
```

## Proposal

eh just do whatever rockstar-js does

## Alternatives considered

While support for closures would be easy for transpilers targeting platforms with native closure /lambda/Blocks support (e.g. JavaScript, Python, C++11, Objective-C), these semantics may be difficult to implement for standalone compilers and interpreters.

One alternative may be to move this to an optional extension, activated by a specific token in the source, similar to how OpenGL Shading Language extensions are activated.

As for choosing an extension identifier: this functionality would allow <i>chain</i>ing multiple [_Blocks_](https://en.wikipedia.org/wiki/Blocks_(C_language_extension)) of code, which would require a _full_ allocation of _stack_ frames on the heap for long lived variables. Thus, I propose the name "fullstack blockchain Rockstar" for this language variant.

## Effect on ABI stability

[Hahahahahaha](https://github.com/apple/swift-evolution/blob/master/proposal-templates/0000-swift-template.md#effect-on-abi-stability) no

## Todo

- [ ] Ask for help in rewriting this example in idiomatic Rockstar, because I only listen to music by Justin Bieber

### CODE REVIEW

**Comment by wolfgang42** [comment]
> an optional extension, activated by a specific token in the source

I don't think there needs to be a setting to activate it: just say it's optional and the implementation should complain if it encounters nested functions but doesn't support them.

> I propose the name "fullstack blockchain Rockstar" for this language variant.

:+1: :laughing:

**Comment by marcinruszkiewicz** [comment]
@dylanbeattie we actually got nested functions now, so this might be closed, no?

The attached treesort program works for me with minor changes:
- one is it doesn't parse right away, because it uses Right for variable which should be named something else
- other is implementation specific as Ruby doesn't really have nested functions and I'm cheating a bit (and I didn't expect to pass the nested function around, but I can make it work somehow I think)

**Comment by gaborsch** [comment]
From nested functions it is just one step forward to function variables... hmmm, how beautiful would it be to pass a comparison operator to a treesort using arrays...

**Comment by dylanbeattie** [comment]
There's some very interesting stuff here, but I *think* all of it is now supported in Satriani and in the latest version of the language spec, so I'm closing the PR as part of a long-overdue clean up of outstanding PRs.

**Pull request closed without merging**
