### PR TITLE
Create c-to-f.rock

### PR DESCRIPTION
**Pull request by PaperFixie**
Submitting this for consideration as an example, and to get my certified Rockstar developer badge.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Badges aren't made yet sorry, things have stalled for a bit in that department (see #36). Just for the record, what does this example have that the others don't (not that I'm saying that more examples are bad, just giving more reason to put it in)

**Comment by PaperFixie** [comment]
@yanorestes thanks, I may have been confused with variables being able to start with a possessive pronoun, but didn't realize it was limited to `a`, `an`, `the`, `my` or `your`. I also didn't realize that the blank space terminated the block, I was looking at the example in the docs and I think I was confused that the `while` statement was being terminated before the end of the function. I'll modify the script to recognize that.

The tests I'm a bit confused on. Shouldn't telling it `function taking argument` allow it to evaluate properly? Or do I have to declare a variable first?

**Comment by marcinruszkiewicz** [comment]
To be honest that's also not really the proper conversion formula.

```
Devilish Secret takes a whisper
The spell is abracadabra. complete
A demoneye is eye unforgivable
Put a whisper of the spell into the grimoire
Give back a demoneye with the grimoire

Listen to a whisper
Scream Devilish Secret taking a whisper
```

Yan already explained errors in the variables and blocks. 

The formula is `fahrenheit = (celsius * 1.8) + 32`, but you have a `;` instead of a `.` in the second line, so even giving that it's a typo, it makes `the soul = 9.45`, which is not right.

I had to split up the formula into two lines, because I still have to implement proper math with more than one operation per line, but it also makes the lines shorter and they look better that way (and the whole verse makes more sense).

**Comment by cwfitzgerald** [comment]
Regarding the issue with function calls, Rockstar doesn't allow you to have naked expressions (expressions that are pure and do nothing). You can just repeatedly assign to a garbage variable to get rid of this. 

This would be proper form. https://rockstar.connorwfitzgerald.com/zNAcqBQfcaw

**Comment by yanorestes** [comment]
@cwfitzgerald I don't think that's specified in the docs. It only says "Functions are called using the 'taking' keyword" and the examples that come right after don't even assign the result to a variable. Following the specs as they are rn this would be valid. 

@PaperFixie yes, `function taking argument` should work fine, but you are using variables that have not been declared yet. Actually, I think I get it, you're trying to use poetic number literals as parameters to the function calls, right? [Have a look](https://github.com/dylanbeattie/rockstar#poetic-number-literals), it doesn't work that way

**Comment by PaperFixie** [comment]
@marcinruszkiewicz I assigned a variable earlier that was `their soul` (not realizing that their wasn't a proper variable declaration) to the value of 9 / 5 (with `;` being used just to make it read as a separate clause to human readers) as a way around this. I didn't know that I could write an 11 character word to write 1. But geez that code reads much better than mine!

I'm fairly new to code in general and found this to be a unique challenge to play with. 

@yanorestes Ah I see that now! I'll assign variables to the poetic numbers. I mostly write Python, where this isn't an issue and may have missed that portion of the docs.

**Comment by marcinruszkiewicz** [comment]
@PaperFixie ah, that was supposed to be 9/5, that explains why it didn't look right :) I thought (and I think every implementation does this as well) that it was a poetic numeral assignment, so `their soul = 945`. 

Actually I think we just might have found an error in the spec - there's [the example here](https://github.com/dylanbeattie/rockstar#arithmetic) that says `My world is nothing without your love`, but that should be a poetic number literal, so the result would be `my_world = 7744`, not `my_world = 0 - your_love`. So either this example is wrong (as there's nothing in poetic assignments section about expressions or operations) or it's okay and the poetic type literal should allow it.

As for the 11 character words, it's just length modulo 10, so especially for 1 and 2 it's usually much better and more METAL to write a long word instead :D

**Comment by cwfitzgerald** [comment]
@yanorestes Sorry had a complete brainfart. Even my compiler [allows this](https://rockstar.connorwfitzgerald.com/C1KPf8LcNrE), otherwise how could you call functions that have side effects? Derp

**Comment by cwfitzgerald** [comment]
@marcinruszkiewicz You're very right that the example is wrong. As of right now, Subexpressions are only allowed in a `Put` statement, not in a `is` statement. This can be added if it's a desired feature, but will make poetic literals hard to get right (it is easy to accidentally get a wrong literal instead of an error) so I would strongly advise against it.

**Comment by marcinruszkiewicz** [comment]
@cwfitzgerald I'll make a separate PR with a fix for that in a minute then, so we can keep it separated.

**Comment by marcinruszkiewicz** [comment]
Right, back to the topic on hand then - @PaperFixie do you think you could also write a non-idiomatic version along with this one, similar to how the FizzBuzz example is written?

**Comment by young-steveo** [comment]
If the next word after `is` is a reserved keyword or literal word, it should not be a poetic number, I think.

**Comment by cwfitzgerald** [comment]
@young-steveo See #112 and #117

**Comment by young-steveo** [comment]
Ah yes, let me revise:  

If the next word after `is` is a literal word, it should not be a poetic number, I think.

**Comment by cwfitzgerald** [comment]
Correct, it is not. I'm advising against allowing subexpressions within a poetic type literal. (which is what `A is nothing` is).

**Comment by PaperFixie** [comment]
@marcinruszkiewicz I actually wrote it literally first before I tried to write it poetically. Wow I didn't know my little script would trigger this many comments! I did submit this to get the feedback on it (and so I can say I'm a Rockstar Developer).

Anyways here's the literal version I originally wrote. I'll spend some time to revise it to reflect multiplying 1.8 and follow the other suggestions as well for the poetic version:
`  (Calculates Celcius to Fahrenheit - literal Rockstar)

CtoF takes temperature
Multiplier is 9 over 5
Adder is 32
Put temperature of Multiplier with Adder into Result
Give back Result

  (test function)
CtoF taking 0   (should evaluate to 32)
CtoF taking 30  (should evaluate to 85)
CtoF taking 18  (should evaluate to 64.4)`

**Comment by PaperFixie** [comment]
The previous example I posted was to give an example of where my head was at when I wrote it.

Updated:
```
CtoF takes temperature
Multiplier is 1.8
Adder is 32
Put temperature of Multiplier with Adder into Result
Give back Result

  (test function)
CtoF taking 0   (should evaluate to 32)
CtoF taking 30  (should evaluate to 85)
CtoF taking 18  (should evaluate to 64.4)

**Comment by dylanbeattie** [comment]
This is seriously out of date, and the file in the PR was never actually updated to be valid Rockstar code, so I'm closing it along with a bunch of other out-of-date PRs.

**Pull request closed without merging**
