### PR TITLE
Add Python interpreter

### PR DESCRIPTION
**Pull request by boppreh**
I've created a Python 3.6 implementation complete enough to run both FizzBuzz examples. There were mistakes in the examples (and the specs) that had to be fixed, though.

I liked the idea of the language, and I had fun implementing an interpreter. The code is terrible, but I think it's in spirit of the joke ;)

Main problems I found and fixed:

- Examples are using `greater than` when it should be `>=`.
- `Midnight taking Desire, Fire` should be `Midnight taking my world, Fire`.
- Loops are inconsistently defined. The `Until Counter is Limit` should only include the very next line, because the rest doesn't start with `and`. The way I implemented you, if the second line doesn't start with `and`, then the loop blocks goes until EOF, `And around we go` or `End`. Not intuitive, but requires the least changes in the examples/spec.
- If you use `Midnight taking Desire and Fire` instead of `Midnight taking Desire, Fire` in a conditional, the grammar becomes ambiguous (is that "and" separating the parameters or a boolean OR?).
- Probably more that I forgot.

### CODE REVIEW

**Comment by dylanbeattie** [comment]
I've updated the block syntax so that blocks now have to end with an explicit blank line - it should make parsing blocks much easier. I'll hold off merging this until you've had a chance to look at the new syntax.

**Comment by NullVoxPopuli** [comment]
Are those problems solve by an AST?

**Comment by boppreh** [comment]
That was quick!

Thanks for the update. Working on it...

**Comment by boppreh** [comment]
Done, updated with the latest version of the specs. The block delimiter rules were my biggest complain, and the extra operators are welcome (and creatively named!).

**Comment by NullVoxPopuli** [comment]
I may try a Ruby version demonstrating an AST

**Comment by boppreh** [comment]
Ok, I've added AST printing too. Here's what the fizzbuzz looks like:

```
[('function',
   'Midnight',
   ['your heart', 'your soul'],
   [('while',
     ('binop',
      ' is as high as ',
      ('name', 'your heart'),
      ('name', 'your soul')),
     [('put',
       'your heart',
       ('binop', ' without ', ('name', 'your heart'), ('name', 'your soul')))]),
    ('give back', ('name', 'your heart'))]),
  ('is (assignment)', 'desire', 100),
  ('is (assignment)', 'my world', 0),
  ('is (assignment)', 'fire', 3),
  ('is (assignment)', 'hate', 5),
  ('until',
   ('binop', ' is ', ('name', 'my world'), ('name', 'desire')),
   [('build', 'my world'),
    ('if',
     ('binop',
      ' and ',
      ('binop',
       ' is ',
       ('taking',
        ('name', 'midnight'),
        [('name', 'my world'), ('name', 'fire')]),
       ('string', 0)),
      ('binop',
       ' is ',
       ('taking',
        ('name', 'midnight'),
        [('name', 'my world'), ('name', 'hate')]),
       ('string', 0))),
     [('shout', ('string', 'FizzBuzz!')), ('continue',)]),
    ('if',
     ('binop',
      ' is ',
      ('taking',
       ('name', 'midnight'),
       [('name', 'my world'), ('name', 'fire')]),
      ('string', 0)),
     [('shout', ('string', 'Fizz!')), ('continue',)]),
    ('if',
     ('binop',
      ' is ',
      ('taking',
       ('name', 'midnight'),
       [('name', 'my world'), ('name', 'hate')]),
      ('string', 0)),
     [('say', ('string', 'Buzz!')), ('continue',)]),
    ('whisper', ('name', 'my world'))])])
```

**Comment by NullVoxPopuli** [comment]
Is there a website that provides a REPL so you can try out PR'd code and such in-browser?

**Comment by boppreh** [comment]
@NullVoxPopuli there's Try It Online. [Here's a direct link to the program running fizzbuzz and printing the AST](https://tio.run/##3Rtdk9u28Z2/AjlPhqQtq6dJ@6KJmklSJ00TuxnHSR5kVQNJoIQeBXII8C465367u7sAQZCibN1dp5OpH07kEljsF/YLcHkwu0J99v693JdFZVglouaJq02xb960qaTaRllV7FlZwrNh7ot9iyI7fqn4XrAZy/l@teFTFu8PLGbPWByP/11IldhR4/WukGuRWKxjrtdSLvPiRlRrrkXKsqJikkmFRGxFMrlM06hWQq95KZZ2kl/DkTZ1v/PJ9PlkMa5EmXNYIX77VsUjFsPfNAQaApou8G1M0LgLvUDgRZxG0UZkTPxmKr42jgqdrIuNSKcRg38XFxf0@9rO1YznOculERXPHXUamTI7wbbyWiiGk9mNNDt4UtpwZfQIVGDqSqG0ERkOdsRs7HiQIEENX@WCFVk7d8ze7KRmN/zAbgTbFCo2bMevYWhBuG6KqjowvirqRqENeZrtuVnvEHIlDjBuo2kdbeosG7O/ycocRuw7dqWKG0K1AhQw7EqzYsd0Aevl@bgjhYbhGXt3RwCUXiNWWs2JDf85qwlsKEn9R4dpjuAFjOpZgkU2dup3LyVXSTq/XEw775PFokVr5UxLR8F7Jca6XiVVfJHM/3Wx@B0MIH36xcXvb2N4fxsj4G0MEDIWx8@INJOOGlKtqZS80sIyg39GTKjrnqm8Kqo9z@UtGgtR4lSY1WptZKEYPINujcjqnK3EmtdakPJz2Bg13wocsK747aErfCdPwkj7yolTZvYTWGESS9oEO4F/tf3Zyb2FVfgDC@3d7yEOtOUkBezM42W8IHjz4laN@hIOJNIwl2Sy0maZSwWy0UIZoWDXDInpW9otyDdNYTgFLZ8gjag2Yp3ziuPziPZEvQexerxgNkbmVgq4LUDIUknge0NkoenbvQb4HepVsQGrx31gOdHdBT2fOGINm502JE7qKqOZsLRWAKvxvUbjBVm1IgAbhc2YxLCvr4Da2CpMCxxuChyLqkAN2l8VIhI52EVMhMQ0z36DSfPACglo5Usult67mBwVftnUaheZWmYKlENPCqwdkVvcq7xYXyU9BbZbvlbJ02ue10IHJgRs5EJZinTKPpnR69EwsiIugblf8NOLqiqqJItfSk37GhWl6v1KVPjEqy2oHPwgMefV9K4jf8bupuDES7E2oPl3ARF3LHlnH@9SkuS2MHaAIwsH2Me7dBy3jgRXs6oFClCct7J0SEdskCXcLI03gzn9jQUiW6Kck0bsabideuYEg0ewmRsoGMegvYWag1C2kqooyTkTamc60yam5iIzgFpud2bqYzkCEysa@pKkIzcZBHDeXBjop7q54MBgL@4Air/nofnrrE@BxbKtBDePR7OS28cjgc1UqAfi6SAC/30@ls9PUAOb2oBzejQe2HeQ1DwazY3gVw/D0qJBk4GNb3ZcnSviAWLIZB6PBkxm@3gs1mYejKdFRDH/Plg@H6AmF1o/FgfZy@NJQXt5MBZC8wRyLYO5EzgIgylWJXIJQQwCBGS7ooJgsJFryKHbRc9baHZsnGVenzv7WZ9ZqgYeOHcv1dkLPx9aGAuDB043ErOt8yY/PYof2YNnXotzY8@f2rl3QTYKuQDkfBrzUQPF3VD6@bpWz4vsOSR/z/cS3B@Og5rKxnZMNYEIRNBN@57AvBwT@0owBakElkiYEUGut2HguSDX/0cNyaaBmqyoK0jvtRlHTZqOa4yl3sgtpGPHuXfDG5TeRHZqJ2Iq4nM3yAQUpiM21o@h0tvrpJuDtekl1qWAp5unoOQwK3QidTkrkdbLE0dskh5PzSA1oQdMO3y@GEi8XcDnjJ5RWhEx2KdTKDxlQzhcxuQWapFlKsWkiSQTj0KReXLDddOuWqAiq4zGDZPEqNlubaTdQvhwimhEM//z9LgabfSKaBFDQnTCWxxgbMmhagFLl/hYgQPVRqC5dmZHdUg5TjxJeVvJ@jluiZJDLdNWHMGc8@sOLG1cyXFUxcAUPxmIRPpaFLR4b6IvU@Y0@OzJPVWA9aTJU8tEMshASkqy8owD@Y1COpzSXGUeVGWt1@mX6ACjbBuNoakvE187nHYKfgiSZVsS8aiF2nWwZDwPAz44ttKwjh@s@7qe8@sTZbgtr3E@TNrAVHhXnSqbPnYdalMNoUaDstRr2cJudhISXb9ex92hIP2X@eViPll0HZ7/OC6LMrnsepMVpIpXQVcK8kYsN505eZ2COpf@42BZHDIz5mUJIkj8jN4Q4q4ZZDd/oK@hujyKnrCfoWL@kVq7sWYvfluLkkphfdCwCJlwUQrbK9E2J4JAIqqqLg3GM0hDc5ZBEjmO1jmHLBD0aCC5EInHlU6BX63d969QNKc@viZaw6@@ObBcSiXNcgliyjNXLAd2jdCxjbIz@7HTWfugpE8YIsdWpzoEBgkQJeBBcwjEENWdaDnDnhCYUhi3o47mu@Z50vCwu6OKtsUFvJy0M4rJ9tt0wPhskMeekQ0HASrv18mh2@BAUcEvS00iLybwtK6HYXtqrhfVbxd69A5uW4fYo8I2GoiLWtEUReO1s5IwHrq9kbQfRy23TX9osOPjba7xVyepIdkgOZviRn2ClBBkkAz75VwarF0HBPj2XCjZbsy1uQgF0tAv@K5nq4BTvuE4RrR4OwPDPlKmWmdeq@AI5lWhRMuAU/aMxWSv8fTII92zx0eYfayn1Cd4PZm1CW36XDcqsoQdoel2sD6iPrsZO3T1h9DpSnU4BjoRDrXgOk088mfeTIfxNFZ/ajYZ2PDUNtz0FEcR9I@oOEvYf0NxGKj/P5Unsz@i5oCqx6lNZh/X1wm1dB17WFvhsQ9bcUgSQ1d@f849cn@qG2CmOHhKLttm3LF4zowgLvnpCacTUeTJcPLEngZe4MALtsduwUownmHDEoxzIzGg8Nwmy5ptagzFbPYWDA2cv9zW0rizqG5wsge8MzzrzOo8p7OUpIqT8bMvUiSHHuI2QKXjbVXUpU46iYrFQhEY9uvOVhnweIPNDfuImo57cmnyuctWo3mDbajjEc7BdgcNDDZCp47pjW2uHQDXCZ7k4Nz008mlLePwDem3S3vjGNMB2zhOXUqVpg8Ize3WAnFCFiy3irJ7V0g1ue7HjCiM8DYBHvApZW0Cp0LDLEUNbceq/rE2zKlbgcn0FQ75S863egazvvv21T9fv/j6y59eDFjB/fdiQN3Dch4vWOS6EeZ992Yo1t7WHBLwqpb5Jh5K844E@xUOdaKtyweI9P6CsNQ1BfrZnD@bsckQs1cKnMl5zH6PQx2zmHv/T9i19N2b3ecn2MV8vs9t25ak17D52ZPAGyyErADobtRDN5JfdkAWJ5qkLWkDc051Rb0Uie1Ru27I6kelCnEJ@f7lyx9@fmH5fvXlyxeDgrcYSfwehOsthnSRSw1SG7C9Y8H/QEPZI3zXsOWdkpcj7d5mh3EIPFUy1HRrLw7YmGVbfseNehdvfQvQhg57QatXEIf5E1E6HUheH5o/zTGEEtZnk@lioN8eSuwjjvkjAuwEs@Hs6XRr7iglGLpD8iNyyQS@4SEgXSl6Z1s1d1NWq0qsi62St6IVMt1khDSh8hJJ0@Z08XshSovEXUgJteNPjHYiL4HlVb3d4sXHsJWXJP0@UUqXO1LbRwgaX0N3Dt9UXOmcG2y1FnW1FvauIAV3ztB48ZAN0Cm6pORbWJCc0Imjp4mw7YXhG2542u1wYT@6uTFCx29QrOlSVPGU0SXQUftF88MQFE8Yh@Br0N@@/dB@aRLLKbschVCbY/ahhXKwFmiqGmFv4CcYehD6GEie6hhcXHlYC8w42BjAv8HfDg0DwBs81T93MJ5KN2CC3jUm5u6VDl4r7V4itTcywWEoCMvgYrQ5NDd4Laqg@7up6SKouwNnFb6m8q@9wTl46bUxiXFdgq00l3l12r8OSP2nqNNdx@4UmGQiYK8gISKZBwVgJcskZqM4dceZbg9Je1@26XPijd4FEgn@bjZxPiGwa38gcO75wCMb@u3SH2jpf7ib36KwJLh7pJ262e17lMyQw/Ao6OAXxgfFJG2uJJ5BEDuaGZ1sqrSch2k/9T9eu065Zn136y6IjtuSpeEkdF6escCtzS8X4FMlHg1Q8F9SYrBc7rlUy6VLDTJ5e7uqb29BR@ibXsqNojzI9mYPeJq@E2AX5ITpFZxiHv1Kqg8@d@@etQOxOgqGNVcj/ADrV9sRUdQ2FEJo9DehZUWXdMEJF9cCjLuGMTnfHK4kXoyJXh6w/ISSAcY4Z8eib9wkuRbR30H8dAUGrylFP9Pp2T6YZJcYRbbw8F/qMvouY6FkEHPzecSaJZo1UVKnRzdEuNHRTySPi29AD1@BHj65iN4cnQhE9yIgRPkQdEcU8gO7@ABtv9rQ5TFEaEj20MP9j4eDjoKbqvA65tX2Gi9cTVprJ78L3rQdMJ8sUrSmrLclwPSzMYS5Tdv9CbMUfyUVHFWMQojZU5bITz@bzS7xqk@MvDjYXwiGvtFUiTz@7xIjNrmchMfodufbXdbsnSCLItoa8Pv3/wE).

**Pull request closed without merging**
